# Configuration for pre-commit hooks
# See https://pre-commit.com for more information

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Using a recent stable version
    hooks:
    -   id: check-yaml # Checks YAML file syntax
    -   id: end-of-file-fixer # Ensures files end with a newline
    -   id: trailing-whitespace # Trims trailing whitespace
    -   id: check-added-large-files # Prevents committing large files

-   repo: https://github.com/psf/black
    rev: 24.4.2 # Using a recent stable version compatible with Python 3.x
    hooks:
    -   id: black # Formats Python code

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Using a recent stable version
    hooks:
    -   id: flake8 # Lints Python code
