"""Add approval_notes to Match

Revision ID: 7800133a9ad6
Revises: fa62b27018b8
Create Date: 2025-03-31 18:32:51.233908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7800133a9ad6'
down_revision = 'fa62b27018b8' # Reverted dependency
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('approval_notes')

    # ### end Alembic commands ###
