"""Add profile fields to User model

Revision ID: b1c4068237c6
Revises: 7800133a9ad6
Create Date: 2025-04-06 20:52:29.862240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c4068237c6'
down_revision = '7800133a9ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('retirement_plane', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('retirement_plane')
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
