"""Add is_pauper and details to Game model

Revision ID: fa62b27018b8
Revises: f2f7afdc1ebd
Create Date: 2025-03-31 17:36:00.079396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa62b27018b8'
down_revision = 'f2f7afdc1ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        # Provide server_default='false' for existing rows
        batch_op.add_column(sa.Column('is_pauper', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('is_pauper')

    # ### end Alembic commands ###
